# Generated by Django 4.1.4 on 2023-04-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0018_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(default='Description goes here', max_length=700)),
                ('count', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=1000)),
                ('sell', models.CharField(blank=True, max_length=10000000000)),
                ('expense', models.CharField(blank=True, max_length=10000000000)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmsapp.depstock')),
            ],
        ),
    ]
