# Generated by Django 4.1.4 on 2023-04-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0019_depstock_livestock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dam',
        ),
        migrations.DeleteModel(
            name='Debtors',
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
