# Generated by Django 4.1.4 on 2023-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0020_delete_dam_delete_debtors_delete_fish_delete_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(default='Description goes here', max_length=700)),
            ],
        ),
    ]
