# Generated by Django 4.1.4 on 2023-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0022_alter_depstock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depstock',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
