# Generated by Django 4.2 on 2023-04-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0023_alter_depstock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=700)),
                ('landarea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveFarmStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(blank=True, max_length=1000)),
                ('quantity', models.CharField(blank=True, max_length=1000)),
                ('sell', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('harvestdate', models.CharField(max_length=10)),
                ('sellingdate', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('farmdepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmsapp.farmstock')),
            ],
        ),
    ]
